apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-toolkit
  namespace: devops-toolkit
spec:
  project: default
  source:
    repoURL: https://github.com/Ashikuroff/devops-toolkit.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: devops-toolkit
